Update vdr-recordingaction
Typo

diff --git a/debian/vdr-recordingaction b/debian/vdr-recordingaction
--- a/debian/vdr-recordingaction
+++ b/debian/vdr-recordingaction
@@ -48,5 +48,5 @@ for rec_hook in "${REC_HOOKS_DIR}"/R[0-9][0-9].* ; do  # Only match 'R<XX>.<iden
       logger -t "$SELF_NAME" "Executing $rec_hook $action as shell script"
       /usr/bin/sh $rec_hook "$@"
     fi
-    [[ $? -ne 0 ]} && logger -t "$SELF_NAME" "Error when executing $rec_hook"
+    [[ $? -ne 0 ]] && logger -t "$SELF_NAME" "Error when executing $rec_hook"
 done
