Made valgrind a Suggests and check in vdrleaktest, if valgrind exists (Closes: #489003) SVN: trunk@7042

diff --git a/debian/vdrleaktest b/debian/vdrleaktest
--- a/debian/vdrleaktest
+++ b/debian/vdrleaktest
@@ -45,6 +45,15 @@ do
 done
 
 #
+# Check for Valgrind
+#
+
+if [ ! -x /usr/bin/valgrind ] ; then
+    echo "ERROR: Please install valgrind first!" >&2
+    exit 1
+fi
+
+#
 # c't-VDR Memory Leak Tester
 #
 
